version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          cluster: test-cluster
          deployment: test-server-app
          container: test-server-container
          image: gcr.io/crucial-limiter-258015/test-server:v6 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: dev
          extra_build_args: "--build-arg token=$NPM_TOKEN --build-arg se=1"
          image: test-server
          tag: "v6" #Change version number when updating application
      - deploy:
          context: dev
          requires:
            - gcp-gcr/build-and-push-image